### ISSUE TITLE
Package gorequest broken

### ISSUE THREAD

**Issue by tonytcb** [moul/http2curl#20]
Since today,  I'm facing the below issue with the package "gorequest" about this package.

Did something change? Can I do something in my app to fix it?
```
../github.com/parnurzeal/gorequest/gorequest.go:31:2: cannot find package "github.com/moul/http2curl" in any of:
	/usr/local/go/src/github.com/moul/http2curl (from $GOROOT)
	/go/src/github.com/moul/http2curl (from $GOPATH)
```

Thanks in advance,

**Comment by moul** [comment]
Hi @tonytcb,

Yes, `http2curl` was bumped to version 2 today (See https://github.com/moul/http2curl/pull/19)

As soon as I made the v2 release, I opened pull request on most popular depending projects, including gorequest (see https://github.com/parnurzeal/gorequest/pull/234)

It's now merged on gorequest, so you should only have to bump gorequest to the latest version and things should go green again for you

For you information, gorequest is one of the rare popular golang project I know that dont use any vendoring system, by adding go mod support on the end repo, we should reduce the amount of issues like these

Tell me if upgrading gorequest solved your issue or if I can help

**Comment by moul** [comment]
Related with https://github.com/parnurzeal/gorequest/issues/235

**Comment by tonytcb** [comment]
@moul Thank you!

Issue solved in the gorequest package.
