### ISSUE TITLE
Difference to net/http package

### ISSUE THREAD

**Issue by tonytcb** [moul/http2curl#21]
Hi. I'd like to know what is the differences between use the curl command to use the native net/http package to perform http requests. I mean, there's differences in DNS resolution, timeouts, or any configuration that could work different to the same request?

I'm asking this because before I was using a 3rd party package that use this http2curl package to perform the requests, and now, I'm using another one that uses the net/http package.
Unfortunately, for the same request, I'm seeing o lot of timeouts which dit not happen before.

Thanks in advance.

**Comment by moul** [comment]
Hi @tonytcb, this package is not a competitors to net/http, it won't make any request; this package is about printing the equivalent curl command of a specific net/http request

It's useful for devs :)
