### ISSUE TITLE
[BUG] expects import

### ISSUE THREAD

**Issue by richardsonlima** [moul/http2curl#27]
**Describe the "bug"**
It's a little replacement that could solve an issue into doc.go file, if you don't mind take a look into it to be noticed that you should remove  "// import "moul.io/http2curl/v2" from github.com/moul/http2curl/doc.go 'cause it's reproducing the error below

../../gopkg.in/ns3777k/go-shodan.v3/shodan/shodan.go:7:2: code in directory /Users/richardsonlima/go-workspace/src/github.com/moul/http2curl expects import "moul.io/http2curl"

**Versions:**
- OS: [Mac 11.0.1 (20B29)]
- Golang version [go1.15.4 darwin/amd64]

**Comment by moul** [comment]
thank you @richardsonlima :)
