### ISSUE TITLE
[BUG] http: ContentLength=xx with Body length 0

### ISSUE THREAD

**Issue by ioito** [moul/http2curl#48]
**Describe the bug**

after https://github.com/moul/http2curl/pull/31 merged

client.Do(req) https request will return `http: ContentLength=xx with Body length 0` error after http2curl.GetCurlCommand(req) called

**To Reproduce**

    str := `{"hello":"world"}`
    req, _ := http.NewRequest("POST", `https://www.baidu.com`, strings.NewReader(str))
    req.Header.Set("Content-Length", strconv.FormatInt(int64(len(str)), 10))
    client := &http.Client{
        Transport: &http.Transport{
            TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
        },
    }
    http2curl.GetCurlCommand(req)
    _, err := client.Do(req)
    if err != nil {
        fmt.Println("err: ", err)
    }

/cc @Dzalevski

**Comment by Dzalevski** [comment]
Hello @ioito http2curl.GetCurlCommand(req) -> this is returning the actual curl cmd and the error you need to use that command in execution

**Comment by Dzalevski** [comment]
![image](https://user-images.githubusercontent.com/9572827/131469776-839d1580-f7e5-446d-a84b-636846815a6e.png)

**Comment by Dzalevski** [comment]
It's okay in my test

**Comment by Dzalevski** [comment]
@ioito @moul Yes. GetCurlCmd after reading from the body will be empty it :) -> it was made for a performance boost. 
maybe you can make a duplicate buff for req.
